# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Yarn
      run: npm i -g yarn

    - name: Install Deps
      run: yarn

    - name: Run Build
      run: yarn run build

    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with: 
        branch: gh-pages
        folder: build
    
    
    
